code --install-extension bibhasdn.git-easy
code --install-extension capaj.vscode-exports-autocomplete
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension IBM.output-colorizer
code --install-extension ionutvmi.path-autocomplete
code --install-extension jingkaizhao.vscode-redux-devtools
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension plievone.vscode-template-literal-editor
code --install-extension robinbentley.sass-indented
code --install-extension vikas.code-navigation
code --install-extension wk-j.webpack-progress
code --install-extension xyz.local-history